### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by joker108** [OphiteCorp/vhackos-botnet#1]
Hello
When will there be an update ?
[UpdateService] An unexpected error occurred while processing the service
hd.vhackos.b0tnet.api.exception.InvalidRequestException: The server returned error 10, this might mean the bot is outdated, bug ocurred or invalid request
	
.....

**Comment by mimic2300** [comment]
Hi, what version do you use?

**Comment by joker108** [comment]
I have loaded 1.0.2. Until yesterday he went without any problems
Today only errors come
`[INFO ] 2018-08-11 16:42:36.510 [  1] [Application] The B0tnet starting in version: v1.0.2
[INFO ] 2018-08-11 16:42:36.632 [  1] [Reflections] Reflections took 83 ms to scan 1 urls, producing 4 keys and 25 values 
[INFO ] 2018-08-11 16:42:36.681 [  1] [Reflections] Reflections took 29 ms to scan 1 urls, producing 1 keys and 13 values 
[INFO ] 2018-08-11 16:42:36.749 [  1] [Reflections] Reflections took 59 ms to scan 1 urls, producing 7 keys and 104 values 
[INFO ] 2018-08-11 16:42:36.839 [  1] [ConfigProvider] Configuration from file 'b0tnet.properties' was loaded
[INFO ] 2018-08-11 16:42:36.884 [  1] [B0tnet] Checking the latest version of B0tnet. Please wait...
[INFO ] 2018-08-11 16:42:36.902 [  1] [Reflections] Reflections took 17 ms to scan 1 urls, producing 4 keys and 25 values 
[INFO ] 2018-08-11 16:42:36.904 [  1] [B0tnetUpdateService] Starting...
[INFO ] 2018-08-11 16:42:37.558 [  1] [B0tnetUpdateService] Your B0tnet version is up to date ;-)
[INFO ] 2018-08-11 16:42:37.559 [  1] [B0tnetUpdateService] Information about the latest version of B0tnet was obtained. Next check will be in: 01h 00m 00s
[INFO ] 2018-08-11 16:42:37.562 [  1] [B0tnet] Getting user 'mynyme xD' information. Please wait...
[INFO ] 2018-08-11 16:42:37.735 [  1] [UpdateService] Starting...
[ERROR] 2018-08-11 16:42:39.336 [  1] [UpdateService] An unexpected error occurred while processing the service
hd.vhackos.b0tnet.api.exception.InvalidRequestException: The server returned error 10, this might mean the bot is outdated, bug ocurred or invalid request
	at hd.vhackos.b0tnet.api.net.OpcodeRequest.send(OpcodeRequest.java:230) ~[b0tnet.jar:?]
	at hd.vhackos.b0tnet.api.module.base.Module.sendRequest(Module.java:82) ~[b0tnet.jar:?]
	at hd.vhackos.b0tnet.api.module.CommonModule.update(CommonModule.java:102) ~[b0tnet.jar:?]
	at hd.vhackos.b0tnet.service.UpdateService.execute(UpdateService.java:49) ~[b0tnet.jar:?]
	at hd.vhackos.b0tnet.service.base.Service$Run.run(Service.java:305) [b0tnet.jar:?]
	at hd.vhackos.b0tnet.service.base.Service.start(Service.java:108) [b0tnet.jar:?]
	at hd.vhackos.b0tnet.B0tnet.start(B0tnet.java:102) [b0tnet.jar:?]
	at hd.vhackos.b0tnet.Application.main(Application.java:127) [b0tnet.jar:?]
[INFO ] 2018-08-11 16:42:39.350 [  1] [Application] The b0tnet was started in: 2852ms
[INFO ] 2018-08-11 16:42:39.350 [  1] [Application] Type ".help" to view available commands
[INFO ] 2018-08-11 16:42:39.408 [ 20] [MinerService] Starting...
[INFO ] 2018-08-11 16:42:39.408 [ 23] [NetworkService] Starting...
[INFO ] 2018-08-11 16:42:39.427 [ 22] [ServerService] Starting...
[INFO ] 2018-08-11 16:42:39.428 [ 21] [MalwareService] Starting...
[ERROR] 2018-08-11 16:42:41.790 [ 20] [MinerService] An unexpected error occurred while processing the service
hd.vhackos.b0tnet.api.exception.InvalidRequestException: The server returned error 10, this might mean the bot is outdated, bug ocurred or invalid request
	at hd.vhackos.b0tnet.api.net.OpcodeRequest.send(OpcodeRequest.java:230) ~[b0tnet.jar:?]
	at hd.vhackos.b0tnet.api.module.base.Module.sendRequest(Module.java:82) ~[b0tnet.jar:?]
	at hd.vhackos.b0tnet.api.module.CommonModule.update(CommonModule.java:102) ~[b0tnet.jar:?]
	at hd.vhackos.b0tnet.service.MinerService.execute(MinerService.java:43) ~[b0tnet.jar:?]
	at hd.vhackos.b0tnet.service.base.Service$Run.run(Service.java:305) [b0tnet.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
[ERROR] 2018-08-11 16:42:43.962 [ 23] [NetworkService] An unexpected error occurred while processing the service
hd.vhackos.b0tnet.api.exception.InvalidRequestException: The server returned error 10, this might mean the bot is outdated, bug ocurred or invalid request
	at hd.vhackos.b0tnet.api.net.OpcodeRequest.send(OpcodeRequest.java:230) ~[b0tnet.jar:?]
	at hd.vhackos.b0tnet.api.module.base.Module.sendRequest(Module.java:82) ~[b0tnet.jar:?]
	at hd.vhackos.b0tnet.api.module.TaskModule.createTaskResponse(TaskModule.java:122) ~[b0tnet.jar:?]
	at hd.vhackos.b0tnet.api.module.TaskModule.getTasks(TaskModule.java:28) ~[b0tnet.jar:?]
	at hd.vhackos.b0tnet.service.NetworkService.prepareWorkData(NetworkService.java:150) ~[b0tnet.jar:?]
	at hd.vhackos.b0tnet.service.NetworkService.execute(NetworkService.java:81) ~[b0tnet.jar:?]
	at hd.vhackos.b0tnet.service.base.Service$Run.run(Service.java:305) [b0tnet.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
[ERROR] 2018-08-11 16:42:45.282 [ 21] [MalwareService] An unexpected error occurred while processing the service
hd.vhackos.b0tnet.api.exception.InvalidRequestException: The server returned error 10, this might mean the bot is outdated, bug ocurred or invalid request
	at hd.vhackos.b0tnet.api.net.OpcodeRequest.send(OpcodeRequest.java:230) ~[b0tnet.jar:?]
	at hd.vhackos.b0tnet.api.module.base.Module.sendRequest(Module.java:82) ~[b0tnet.jar:?]
	at hd.vhackos.b0tnet.api.module.CommonModule.update(CommonModule.java:102) ~[b0tnet.jar:?]
	at hd.vhackos.b0tnet.service.MalwareService.execute(MalwareService.java:39) ~[b0tnet.jar:?]
	at hd.vhackos.b0tnet.service.base.Service$Run.run(Service.java:305) [b0tnet.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
`

**Comment by mimic2300** [comment]
Yeah, cuz game was updated over night. This github is dead, for next news follow discord channel

**Comment by joker108** [comment]
ok
